<html><head><title>Flumpshop | Setup</title></head>
  <frameset cols="252px,*" framespacing="0" border="0" frameborder="0" frameborder="no" border="0">
    <frame name="leftFrame" id="leftFrame" src="?frame=leftFrame#welcome" scrolling="yes" frameborder="0" marginwidth="0" marginheight="0" border="no" />
    <frameset rows="60px,*" framespacing="0" border="0" frameborder="0" frameborder="no" border="0">
      <frame src="?frame=header" name="header" id="header" scrolling="no" noresize="noresize" frameborder="0" marginwidth="10" marginheight="0" border="no" />
      <frame src="?frame=main" name="main" id="main" scrolling="yes" frameborder="0" marginwidth="10" marginheight="10" border="no" />
    </frameset>
  </frameset>
</html>