<script type="text/javascript">
  parent.leftFrame.window.location = '../index.php?frame=leftFrame&p=1.3';
</script>
<h1>Ready To Go</h1>
<p>Right, I've remembered all of that. Now, lets begin with the actual setting up!</p>
<button onclick='window.location = "<?=$setup_next_url?>";
  parent.leftFrame.window.location = "../index.php?frame=leftFrame&p=2.1";'>Begin with the actual setting up!</button>
<script type="text/javascript">$('button').button().click();</script>