<?php
/**
 *  View for the last page of the Setup Wizard
 * 
 *  This file is part of Flumpshop.
 *
 *  Flumpshop is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Flumpshop is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Flumpshop.  If not, see <http://www.gnu.org/licenses/>.
 *
 *
 *  @Name views/setup_finished.inc
 *  @Version 1.01
 *  @author Lloyd Wallis <flump5281@gmail.com>
 *  @copyright Copyright (c) 2009-2012, Lloyd Wallis
 *  @package Flumpshop
 */
?><h1>Goodbye, and hello!</h1>
<p>Hello, and welcome to your new Flumpshop installation. My name is the Flumpnet Robot, and I'm getting a strange feeling I've met you before. It looks like somebody has already taken the time out to set up Flumpshop for you, and it's now ready and waiting for you commands.</p>
<ul>
	<li><strong>Flumpshop is clever.</strong> With me watching your every step, and daily backups by default, you can be assured that whatever you do, there is always a way to get yourself back on your feet.</li>
    <li><strong>Flumpshop is psychic.</strong> Flumpshop can tell when there's an update available, provides you with a notification, and can even download and apply the update as soon as you authorise it, so you always know you'll have access to the latest updates.</li>
    <li><strong>Flumpshop is simple.</strong> Flumpshop was built with complete simplicity in mind. In the Admin CP, no changes are ever more than three clicks away, and with a clever and intuitive UI, you know you can find what you're looking for.</li>
    <li><strong>Flumpshop is comprehensive.</strong> We hate it as much as you do when you have to change the source code or spend hours traipsing through forums to change a simple thing. Throughout the development process, whenever someone said "Wouldn't it look better if...", we didn't change it. Instead, we made a button for you to change it, so you know that if there's anything you're unhappy with, you can fix it in moments</li>
    <li><strong>Flumpshop is evolving.</strong> Flumpshop is entirely open source, and you can post problems, get sample packs, documentation and many other resources at any time by clicking on over to <a href='http://flumpshop.googlecode.com' target="_blank">flumpshop.googlecode.com</a>. This means that even if there is something you can't change by pushing a button, you can tell us to add that button.</li>
    <li><strong>Flumpshop is more than a shop.</strong> Flumpshop can be used for whatever you want. Everything is customisable, so if you wanted, it can even be used as a CMS, and completely disable all shop-related features.</li>
    <li><strong>Flumpshop is extendable.</strong> And this isn't a poorly written spam email about bedroom performance. You can get extensions from the community, or even write your own.</li>
    <li><strong>Flumpshop is not a weapon of mass destruction.</strong> Flumpshop's developers tried their hardest, but unfortunately thus far have not been able to write a PHP module that will configure the server that Flumpshop is hosted on to change into transformer mode and kill all life it comes into contact with. Keep an eye on the Flumpshop Plugins store to see if they're ever successful!</li>
</ul>
<h2>What next?</h2>
<ul>
	<li><a href="../../" target="_top">Click here</a> to go to your Admin CP and begin adding information to your site</li>
    <li><a href="../../../" target="_top">Click here</a> to go to the frontend of your site and see it in its empty glory</li>
    <li><a href="http://flumpshop.googlecode.com" target="_blank">Click here</a> to go to the Flumpshop development site</li>
    <li><a href="http://www.flump.me/" target="_blank">Click here</a> to go to the Flumpnet website</li>
</ul>
